version: 2
sphinx:
  configuration: docs/source/conf.py
python:
  install:
    - requirements: docs/requirements.txt
build:
  os: "ubuntu-24.04"
  tools:
    python: "3.13"
  jobs:
    pre_build:
      - cd docs && ./create-zip.sh
